package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"
)

const (
	deepseekBaseURL = "https://api.deepseek.com/v1"
	defaultModel    = "deepseek-chat"
)

type Service struct {
	apiKey string
	client *http.Client
}

func New(apiKey string) *Service {
	return &Service{
		apiKey: apiKey,
		client: &http.Client{Timeout: 45 * time.Second},
	}
}

func (s *Service) Enabled() bool { return s.apiKey != "" }

type message struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type completionReq struct {
	Model       string    `json:"model"`
	Messages    []message `json:"messages"`
	MaxTokens   int       `json:"max_tokens"`
	Temperature float64   `json:"temperature"`
}

type completionResp struct {
	Choices []struct {
		Message struct {
			Content string `json:"content"`
		} `json:"message"`
	} `json:"choices"`
}

// ChatMessage is an exported turn in a multi-turn conversation.
type ChatMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

func (s *Service) completeMessages(ctx context.Context, msgs []message, maxTokens int, temperature float64) (string, error) {
	body, _ := json.Marshal(completionReq{
		Model:       defaultModel,
		Messages:    msgs,
		MaxTokens:   maxTokens,
		Temperature: temperature,
	})

	req, err := http.NewRequestWithContext(ctx, "POST", deepseekBaseURL+"/chat/completions", bytes.NewReader(body))
	if err != nil {
		return "", err
	}
	req.Header.Set("Authorization", "Bearer "+s.apiKey)
	req.Header.Set("Content-Type", "application/json")

	resp, err := s.client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("deepseek API status %d", resp.StatusCode)
	}

	var result completionResp
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}
	if len(result.Choices) == 0 {
		return "", fmt.Errorf("empty response from DeepSeek")
	}
	return strings.TrimSpace(result.Choices[0].Message.Content), nil
}

func (s *Service) complete(ctx context.Context, systemPrompt, userPrompt string, maxTokens int) (string, error) {
	msgs := []message{}
	if systemPrompt != "" {
		msgs = append(msgs, message{Role: "system", Content: systemPrompt})
	}
	msgs = append(msgs, message{Role: "user", Content: userPrompt})
	return s.completeMessages(ctx, msgs, maxTokens, 0.75)
}

// Chat handles a multi-turn city-aware conversation.
func (s *Service) Chat(ctx context.Context, city string, history []ChatMessage) (string, error) {
	if !s.Enabled() {
		return "", fmt.Errorf("AI not configured")
	}
	if len(history) == 0 {
		return "", fmt.Errorf("no messages")
	}
	system := fmt.Sprintf(`You are Hapa Guide, an expert local insider for %s. Help travelers and residents discover the best of the city with specific, practical, authentic advice. Be warm and conversational — like a knowledgeable friend giving the local scoop. Keep responses to 2-4 sentences. If asked about something unrelated to %s or travel, gently redirect to local topics.`, city, city)

	msgs := []message{{Role: "system", Content: system}}
	for _, m := range history {
		msgs = append(msgs, message{Role: m.Role, Content: m.Content})
	}
	return s.completeMessages(ctx, msgs, 250, 0.8)
}

// GuideTip is a structured guide note generated by AI.
type GuideTip struct {
	Title    string `json:"title"`
	Body     string `json:"body"`
	Category string `json:"category"`
}

// GenerateCityGuide produces AI city guide tips for the given city.
func (s *Service) GenerateCityGuide(ctx context.Context, city string) ([]GuideTip, error) {
	if !s.Enabled() {
		return nil, fmt.Errorf("AI not configured")
	}
	system := `You are Hapa Guide, an expert local insider for cities across Africa and the world.
Return ONLY a JSON array of guide tips — no markdown, no explanation, no code fences.
Each tip has: title (max 60 chars), body (2-3 helpful sentences, max 200 chars), category (one of: food, transport, culture, safety, etiquette, nightlife, nature).
Generate exactly 12 tips covering different categories. Be specific, practical, and authentic.`

	prompt := fmt.Sprintf(`Generate 12 insider guide tips for %s. Focus on things locals know that tourists miss. Return raw JSON array only.`, city)

	raw, err := s.complete(ctx, system, prompt, 2000)
	if err != nil {
		return nil, err
	}

	// Strip any accidental markdown fences
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	var tips []GuideTip
	if err := json.Unmarshal([]byte(raw), &tips); err != nil {
		return nil, fmt.Errorf("failed to parse guide JSON: %w — raw: %.200s", err, raw)
	}
	return tips, nil
}

// SummarizePost returns a one-sentence TL;DR of a post body.
func (s *Service) SummarizePost(ctx context.Context, content string) (string, error) {
	if !s.Enabled() {
		return "", fmt.Errorf("AI not configured")
	}
	if len(content) < 120 {
		return content, nil
	}
	system := `You are a helpful assistant. Summarize the given local community post in ONE concise sentence (max 120 chars). No quotes, no preamble.`
	return s.complete(ctx, system, content, 80)
}

// SuggestHashtags returns up to 5 relevant hashtags for a post body.
func (s *Service) SuggestHashtags(ctx context.Context, content, city string) ([]string, error) {
	if !s.Enabled() {
		return nil, fmt.Errorf("AI not configured")
	}
	system := `You are a social media expert for local African cities. Return ONLY a JSON array of 3-5 lowercase hashtag strings (no # symbol, no spaces). Example: ["food","kampala","streetfood"]`
	prompt := fmt.Sprintf("Suggest hashtags for this local post in %s:\n\n%s", city, content)

	raw, err := s.complete(ctx, system, prompt, 80)
	if err != nil {
		return nil, err
	}
	raw = strings.TrimSpace(strings.Trim(raw, "`"))

	var tags []string
	if err := json.Unmarshal([]byte(raw), &tags); err != nil {
		return nil, err
	}
	// Sanitize
	clean := make([]string, 0, len(tags))
	for _, t := range tags {
		t = strings.ToLower(strings.TrimPrefix(strings.ReplaceAll(t, " ", ""), "#"))
		if t != "" {
			clean = append(clean, t)
		}
	}
	return clean, nil
}

// BoostCopy is AI-generated promotion copy for a hyper-local boost campaign.
type BoostCopy struct {
	Title       string   `json:"title"`
	OfferText   string   `json:"offer_text"`
	Description string   `json:"description"`
	Tips        []string `json:"tips"`
}

// FlashCopy is AI-generated copy for a Hapa Flash (time-sensitive post).
type FlashCopy struct {
	Text string `json:"text"`
	Tip  string `json:"tip"`
}

// GenerateFlashCopy writes a punchy, urgent Flash post for a business event or deal.
func (s *Service) GenerateFlashCopy(ctx context.Context, businessName, category, city, prompt string) (*FlashCopy, error) {
	if !s.Enabled() {
		return nil, fmt.Errorf("AI not configured")
	}
	system := `You are a copywriter for a hyper-local African city app. Write a punchy Hapa Flash post — a real-time, time-sensitive announcement. Rules:
- text: max 140 characters, urgent, specific, creates FOMO. Use time cues: "right now", "next 2 hours", "starting in 20 mins"
- tip: one short tip for making this flash more effective (max 80 chars)
Return ONLY valid JSON {"text":"...","tip":"..."} — no markdown, no explanation.`

	promptText := fmt.Sprintf(`Write a Flash post for "%s", a %s in %s.`, businessName, category, city)
	if prompt != "" {
		promptText += " Context: " + prompt
	}

	raw, err := s.complete(ctx, system, promptText, 200)
	if err != nil {
		return nil, err
	}
	raw = strings.TrimPrefix(strings.TrimPrefix(strings.TrimSpace(raw), "```json"), "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	var copy FlashCopy
	if err := json.Unmarshal([]byte(raw), &copy); err != nil {
		return nil, fmt.Errorf("failed to parse flash copy JSON: %w", err)
	}
	return &copy, nil
}

// GenerateBoostCopy produces AI-written campaign copy for a local business boost.
func (s *Service) GenerateBoostCopy(ctx context.Context, businessName, category, city, hint string) (*BoostCopy, error) {
	if !s.Enabled() {
		return nil, fmt.Errorf("AI not configured")
	}
	system := `You are a marketing expert specializing in hyper-local African business promotions on a mobile community app. Generate compelling, concise boost campaign copy. Return ONLY valid JSON with exactly these fields:
- title: catchy campaign name that creates urgency (max 60 chars)
- offer_text: compelling notification text with a clear, specific benefit (max 80 chars)
- description: 1-2 sentence promo description that feels warm and local (max 200 chars)
- tips: JSON array of exactly 2 short actionable tips for running this campaign (each max 90 chars)
No markdown, no code fences, no explanation — raw JSON only.`

	hintPart := ""
	if hint != "" {
		hintPart = fmt.Sprintf(" The owner specifically wants to highlight: %s.", hint)
	}
	prompt := fmt.Sprintf(`Generate boost campaign copy for "%s", a %s business in %s.%s Make it feel authentic, locally relevant, and create urgency without being pushy.`, businessName, category, city, hintPart)

	raw, err := s.complete(ctx, system, prompt, 500)
	if err != nil {
		return nil, err
	}

	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	var copy BoostCopy
	if err := json.Unmarshal([]byte(raw), &copy); err != nil {
		return nil, fmt.Errorf("failed to parse boost copy JSON: %w — raw: %.200s", err, raw)
	}
	return &copy, nil
}

// GenerateFeedDigest summarises what's happening nearby in 2-3 engaging sentences.
func (s *Service) GenerateFeedDigest(ctx context.Context, city string, snippets []string) (string, error) {
	if !s.Enabled() {
		return "", fmt.Errorf("AI not configured")
	}
	if len(snippets) == 0 {
		return "", fmt.Errorf("no posts to summarise")
	}
	system := `You are Hapa, a friendly local community assistant. Write a vivid 2-3 sentence summary of what's happening in the community right now. Be warm, specific, and conversational — like a friend giving you the local scoop. No bullet points.`

	bullets := strings.Join(snippets, "\n- ")
	prompt := fmt.Sprintf("Summarise what's happening in %s based on these recent community posts:\n- %s", city, bullets)
	return s.complete(ctx, system, prompt, 150)
}
